name: 'Setup'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: oven-sh/setup-bun@v1
      name: Install bun
      with:
        version: 8
        run_install: false

    - uses: actions/cache@v4
      name: Setup bun cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: Install Turborepo
      shell: bash
      run: bun add -g turbo

    - name: Install dependencies
      shell: bash
      run: bun install
