$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - 'node_modules'
  - 'bun.lockb'
words:
  - 'orbitkit'
  - 'lockb'
  - 'ianvs'
  - 'packagejson'
