$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - .tsbuildinfo
  - .gitignore
  - dist
words:
  - acst
  - aest
  - akst
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - bvaughn
  - Byrom
  - clsx
  - cmdk
  - Colm
  - commitlint
  - consts
  - crossorigin
  - datetime
  - Duarte
  - Embla
  - esbenp
  - hookform
  - ianvs
  - lockb
  - lucide
  - Malyavko
  - neonctl
  - neondatabase
  - nextjs
  - nzst
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - peduarte
  - Ratelimit
  - shadcn
  - stylesheet
  - tailwindcss
  - tsbuildinfo
  - tsconfigs
  - tsup
  - Tuite
  - typecheck
  - typeof
  - typesafe
  - vaul
  - viewports
  - WITA
