$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - .tsbuildinfo
  - .gitignore
  - dist
words:
  - astro
  - astrojs
  - autodocs
  - clsx
  - commitlint
  - consts
  - crossorigin
  - datetime
  - esbenp
  - ianvs
  - lockb
  - neonctl
  - neondatabase
  - nextjs
  - orbitkit
  - packagejson
  - shadcn
  - stylesheet
  - tailwindcss
  - tsbuildinfo
  - tsconfigs
  - tsup
  - turborepo
  - typecheck
  - typeof
  - viewports
