name: '🐘 Create Neon DB Branch'
description: 'Steps to create or retrieve PR db branch from Neon'

env:
  # Neon
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

runs:
  using: composite
  steps:
    - name: Get branch name
      id: branch_name
      uses: tj-actions/branch-names@v8

    - name: Create Neon Branch
      id: create-branch
      uses: neondatabase/create-branch-action@v4
      with:
        project_id: ${{ env.NEON_PROJECT_ID }}
        branch_name: web/pr-${{ github.event.number}}-${{ steps.branch_name.outputs.current_branch }}
        username: ${{ env.NEON_DATABASE_USERNAME }}
        api_key: ${{ env.NEON_API_KEY }}

    - name: Set DATABASE_URL
      shell: bash
      run: |
        echo "DATABASE_URL=${{ steps.create-branch.outputs.db_url }}?sslmode=require" >> $GITHUB_ENV
