name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  code-quality:
    name: Code Quality Checks
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup volta
        uses: volta-cli/action@v4

      - name: get node version
        run: node --version

      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: format
        run: pnpm run format:check

      - name: lint spellcheck
        run: pnpm run lint:spell

      - name: lint markdown
        run: pnpm run lint:md

      - name: lint code
        run: pnpm turbo lint

      - name: typecheck
        run: pnpm turbo typecheck
