name: Pull Request CI
on: [pull_request]

env:
  # This enabled remote task caching using Turborepo
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  # Neon
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

  # Authentication
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
  AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
  AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
  AUTH_GOOGLE_CODE_VERIFIER: ${{ secrets.AUTH_GOOGLE_CODE_VERIFIER }}

  # Uploadthing
  UPLOADTHING_SECRET: ${{ secrets.UPLOADTHING_SECRET }}
  UPLOADTHING_APP_ID: ${{ secrets.UPLOADTHING_APP_ID }}

  # Unkey
  UNKEY_ROOT_KEY: ${{ secrets.UNKEY_ROOT_KEY }}

jobs:
  format-lint-typecheck:
    name: Format, Lint & Typecheck
    runs-on: ubuntu-latest

    env:
      # We don't need to validate the environment variables when we are checking the format, linting and typechecking
      SKIP_ENV_VALIDATION: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format check
        run: pnpm format:check

      - name: Spell check
        run: pnpm lint:spell

      - name: Lint markdown
        run: pnpm lint:md

      - name: Lint & Typecheck
        run: turbo lint typecheck

  build-marketing:
    name: Build marketing website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build marketing website
        run: turbo build --filter=marketing

  build-app:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Neon Branch
        uses: ./.github/actions/create-neon-branch
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          api_key: ${{ env.NEON_API_KEY }}

      - name: Build
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        # The build command will also apply schema migrations on the created database branch
        run: turbo build --filter=web

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Neon Branch
        uses: ./.github/actions/create-neon-branch
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          api_key: ${{ env.NEON_API_KEY }}

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: pnpm turbo test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-playwright-report
          path: apps/web/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: marketing-playwright-report
          path: apps/marketing/playwright-report/
          retention-days: 30
